- name: Install prerequisite packages
  become: yes
  dnf:
    name:
      - gpgme
      - unzip
      - gawk
      - javapackages-tools
    state: latest
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Install pinned msopenjdk-11
  become: yes
  dnf:
    name:
      - msopenjdk-11-11.0.29
    state: present
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Install pinned msopenjdk-17 for Cassandra 5.0
  become: yes
  dnf:
    name:
      - msopenjdk-17
    state: present
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Create Cassandra directory
  become: yes
  file:
    path: /etc/cassandra
    state: directory

- name: Add cassandra group
  become: yes
  group:
    name: cassandra
    state: present
    gid: 3000

- name: Add cassandra user
  become: yes
  user:
    name: cassandra
    group: cassandra
    state: present
    uid: 3000
    create_home: no
    home: "/nonexistent"
    shell: "/usr/sbin/nologin"

- name: Creates /var/log/cassandra directory
  become: yes
  file:
    path: /var/log/cassandra
    state: directory
    mode: '0755'
    owner: cassandra
    group: cassandra

- name: Creates /usr/share/nova directory
  become: yes
  file:
    path: /usr/share/nova
    state: directory
    mode: '0755'

- name: Creates /usr/share/nova/lib directory
  become: yes
  file:
    path: /usr/share/nova/lib
    state: directory
    mode: '0755'

- name: Creates /usr/share/nova/agent directory
  become: yes
  file:
    path: /usr/share/nova/agent
    state: directory
    mode: '0755'

- name: Creates /usr/share/nova/rpm directory
  become: yes
  file:
    path: /usr/share/nova/rpm
    state: directory
    mode: '0755'

- name: Download cassandra rpm package
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name cassandra
      --name {{ item }}
      --file /usr/share/nova/rpm/{{ item }}
      --auth-mode login 
      --output none
  when: not usingContainers
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5
  with_items:
    - cassandra-3.11.17-1.cm2.x86_64.rpm
    - cassandra-4.0.12-1.cm2.x86_64.rpm
    - cassandra-4.1.4-1.cm2.x86_64.rpm
    - cassandra-5.0.2-1.cm2.x86_64.rpm

- name: Set permission for downloaded cassandra rpm packages
  become: yes
  file:
    path: "/usr/share/nova/rpm/{{ item }}"
    mode: '0644'
  with_items:
    - cassandra-3.11.17-1.cm2.x86_64.rpm
    - cassandra-4.0.12-1.cm2.x86_64.rpm
    - cassandra-4.1.4-1.cm2.x86_64.rpm
    - cassandra-5.0.2-1.cm2.x86_64.rpm

- name: Download ecaudit
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name ecaudit
      --name ecaudit_c3.11-2.10.0-SNAPSHOT.jar
      --file /usr/share/nova/lib/ecaudit_c3.11-2.10.0-SNAPSHOT.jar
      --auth-mode login 
      --output none
  when: not usingContainers
  register: task_register_var
  until: task_register_var is not failed
  retries: 5

- name: Set permission for downloaded ecaudit
  become: yes
  file:
    path: "/usr/share/nova/lib/ecaudit_c3.11-2.10.0-SNAPSHOT.jar"
    mode: '0644'

- name: Download fluent-logger
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name 3rdparty
      --name fluent-logger-0.3.4-jar-with-dependencies.jar
      --file /usr/share/nova/lib/fluent-logger-0.3.4-jar-with-dependencies.jar
      --auth-mode login 
      --output none
  when: not usingContainers
  register: task_register_var
  until: task_register_var is not failed
  retries: 5

- name: Set permission for downloaded fluent-logger
  become: yes
  file:
    path: "/usr/share/nova/lib/fluent-logger-0.3.4-jar-with-dependencies.jar"
    mode: '0644'

- name: Download cassandra-lucene-index-3
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name 3rdparty
      --name cassandra-lucene-index-plugin-3.X.jar
      --file /usr/share/nova/lib/cassandra-lucene-index-plugin-3.X.jar
      --auth-mode login 
      --output none
  when: not usingContainers
  register: task_register_var
  until: task_register_var is not failed
  retries: 5

- name: Set permission for downloaded cassandra-lucene-index-3
  become: yes
  file:
    path: "/usr/share/nova/lib/cassandra-lucene-index-plugin-3.X.jar"
    mode: '0644'

- name: Download cassandra-lucene-index-4
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name 3rdparty
      --name cassandra-lucene-index-plugin-4.X.jar
      --file /usr/share/nova/lib/cassandra-lucene-index-plugin-4.X.jar
      --auth-mode login 
      --output none
  when: not usingContainers
  register: task_register_var
  until: task_register_var is not failed
  retries: 5

- name: Set permission for downloaded cassandra-lucene-index-4
  become: yes
  file:
    path: "/usr/share/nova/lib/cassandra-lucene-index-plugin-4.X.jar"
    mode: '0644'
- name: Download logback-more-appenders
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name 3rdparty
      --name logback-more-appenders-1.8.5.jar
      --file /usr/share/nova/lib/logback-more-appenders-1.8.5.jar
      --auth-mode login
      --output none
  when: not usingContainers
  register: task_register_var
  until: task_register_var is not failed
  retries: 5
  delay: 10

- name: Set file permissions for logback-more-appenders
  become: yes
  file:
    path: "/usr/share/nova/lib/logback-more-appenders-1.8.5.jar"
    mode: "0644"
  when: task_register_var is not failed

- name: Fetch 3.x cassandra-ldap.jar
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name cassandra-ldap
      --name cassandra-ldap-3.11.14-1.0.0-v2.4.jar
      --file /usr/share/nova/lib/cassandra-ldap-3.11.14-1.0.0-v2.4.jar
      --auth-mode login 
      --output none
  register: task_register_var
  until: task_register_var is not failed
  retries: 5

- name: Set permission for downloaded 3.x cassandra-ldap.jar
  become: yes
  file:
    path: "/usr/share/nova/lib/cassandra-ldap-3.11.14-1.0.0-v2.4.jar"
    mode: '0644'

- name: Fetch 4.0.x cassandra-ldap.jar
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name cassandra-ldap
      --name cassandra-ldap-4.0.7-1.0.0-v2.4.jar
      --file /usr/share/nova/lib/cassandra-ldap-4.0.7-1.0.0-v2.4.jar
      --auth-mode login 
      --output none
  register: task_register_var
  until: task_register_var is not failed
  retries: 5

- name: Set permission for downloaded 4.0.x cassandra-ldap.jar
  become: yes
  file:
    path: "/usr/share/nova/lib/cassandra-ldap-4.0.7-1.0.0-v2.4.jar"
    mode: '0644'

- name: Fetch 4.1.x cassandra-ldap.jar
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name cassandra-ldap
      --name cassandra-ldap-4.1.0-1.1.0.jar
      --file /usr/share/nova/lib/cassandra-ldap-4.1.0-1.1.0.jar
      --auth-mode login 
      --output none
  register: task_register_var
  until: task_register_var is not failed
  retries: 5

- name: Set permission for downloaded 4.1.x cassandra-ldap.jar
  become: yes
  file:
    path: "/usr/share/nova/lib/cassandra-ldap-4.1.0-1.1.0.jar"
    mode: '0644'

- name: Fetch 5.0.x cassandra-ldap.jar
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name cassandra-ldap
      --name cassandra-ldap-5.0.6-1.0.0.jar
      --file /usr/share/nova/lib/cassandra-ldap-5.0.6-1.0.0.jar
      --auth-mode login 
      --output none
  register: task_register_var
  until: task_register_var is not failed
  retries: 5

- name: Set permission for downloaded 5.0.x cassandra-ldap.jar
  become: yes
  file:
    path: "/usr/share/nova/lib/cassandra-ldap-5.0.6-1.0.0.jar"
    mode: '0644'

- name: Download datastax-mgmtapi-agent 
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name mgmt-api
      --name {{ item }}
      --file /usr/share/nova/agent/{{ item }}
      --auth-mode login 
      --output none
  when: not usingContainers
  register: task_register_var
  until: task_register_var is not failed
  retries: 5
  with_items: 
    - "{{ mgmt_3_x_jar }}"
    - "{{ mgmt_4_x_jar }}"
    - "{{ mgmt_4_1_x_jar }}"
    - "{{ mgmt_5_x_jar }}"

- name: Set permission for downloaded datastax-mgmtapi-agent
  become: yes
  file:
    path: "/usr/share/nova/agent/{{ item }}"
    mode: '0644'
  with_items: 
    - "{{ mgmt_3_x_jar }}"
    - "{{ mgmt_4_x_jar }}"
    - "{{ mgmt_4_1_x_jar }}"
    - "{{ mgmt_5_x_jar }}"

- name: Install cassandra-env.sh
  become: yes
  template:
    src: cassandra-env.sh.j2
    dest: /home/azureuser/scripts/cassandra-env.sh.template
    owner: cassandra
    group: cassandra
    mode: "0600"

- name: Install logback.xml
  become: yes
  template:
    src: logback.xml.j2
    dest: /home/azureuser/scripts/logback.xml
    owner: cassandra
    group: cassandra
    mode: "0600"

- name: Install cassandra.yaml.template
  become: yes
  template:
    src: cassandra.yaml.template.j2
    dest: /home/azureuser/scripts/cassandra.yaml.template
    owner: azureuser
    group: azureuser
    mode: "0600"

- name: Create service directory
  become: yes
  file:
    path: /etc/systemd/system/cassandra.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

# https://unix.stackexchange.com/questions/452284/managing-nproc-in-systemd
# we need both nproc and TasksMax
- name: Copy cassandra service override file
  become: yes
  copy:
    src: "override.conf"
    dest: /etc/systemd/system/cassandra.service.d/
    mode: "0644"

- name: Install audit.yaml
  become: yes
  template:
    src: audit.yaml.j2
    dest: /home/azureuser/scripts/audit.yaml
    owner: cassandra
    group: cassandra
    mode: "0600"

- name: Install pip
  become: yes
  dnf:
    name: python3-pip
    state: latest
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Install cqlsh
  become: yes
  pip:
    name: cqlsh

- name: Put telegraf-ioping.sh
  become: yes
  copy:
    src: telegraf-ioping.sh
    dest: /usr/local/bin/telegraf-ioping.sh
    owner: telegraf
    group: telegraf
    mode: "0755"

- name: Put list_cassandra_processes.sh
  become: yes
  copy:
    src: list_cassandra_processes.sh
    dest: /usr/local/bin/list_cassandra_processes.sh
    owner: root
    group: root
    mode: "0755"

- name: Put Telegraf configuration files
  become: yes
  copy:
    src: "{{ item }}"
    dest: /etc/telegraf/telegraf.d/
    owner: telegraf
    group: telegraf
    mode: "0600"
  with_fileglob: "telegraf.d/*"

- name: Put telegraf.conf
  become: yes
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
    owner: telegraf
    group: telegraf
    mode: "0644"

- name: Install nginx for prometheus port open to customer
  when: '"cassandra_image" in group_names'
  become: yes
  import_tasks: includes/install_nginx_certs.yml
  vars:
    ca: "{{ system_ca }}"
    server_cert: /etc/nginx/prometheus_cert.pem
    server_key: /etc/nginx/prometheus_key.pem
    port: 9500
    location: /
    server_port: 9443
     # Disable client cert validation so customers can connect
    # easily. This is read only data so hold off on enforcing
    # a client cert for now.
    client_ca_enabled: false
    # limit each unique IP address to the rate 1 request per second
    # 1 megabyte memory zone mylimit used to store the state of each IP address
    rate_limiting_enabled: true
    limit_req_zone: $binary_remote_addr zone=mylimit:1m rate=1r/s
    limit_req: zone=mylimit

- name: Get  metric-collector-for-apache-cassandra
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name 3rdparty
      --name {{ mcac_version }}.tar.gz
      --file /tmp/{{ mcac_version }}.tar.gz
      --auth-mode login 
      --output none
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Unarchive metric-collector-for-apache-cassandra
  become: yes
  unarchive:
    src: "/tmp/{{ mcac_version }}.tar.gz"
    dest: "/usr/share/"
    remote_src: yes
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Get  metric-collector-for-apache-cassandra beta1
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name 3rdparty
      --name {{ mcac_version_beta1 }}.tar.gz
      --file /tmp/{{ mcac_version_beta1 }}.tar.gz
      --auth-mode login 
      --output none
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Unarchive metric-collector-for-apache-cassandra beta1
  become: yes
  unarchive:
    src: "/tmp/{{ mcac_version_beta1 }}.tar.gz"
    dest: "/usr/share/"
    remote_src: yes
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Install collectd.conf.tmpl
  become: yes
  copy:
    src: collectd.conf.tmpl
    dest: "{{ item }}"
    mode: "0755"
  with_items:
    - "/usr/share/{{ mcac_version }}/config/"
    - "/usr/share/{{ mcac_version_beta1 }}/config/"

- name: Overwrite metric-collector.yaml
  become: yes
  copy:
    src: metric-collector.yaml
    dest: "{{ item }}"
    mode: "0755"
  with_items:
    - "/usr/share/{{ mcac_version }}/config/"
    - "/usr/share/{{ mcac_version_beta1 }}/config/"

- name: Replace collectd_wrapper
  become: yes
  copy:
    src: collectd_wrapper
    dest: "{{ item }}"
    mode: "0755"
  with_items:
    - "/usr/share/{{ mcac_version }}/lib/collectd/usr/sbin/"
    - "/usr/share/{{ mcac_version_beta1 }}/lib/collectd/usr/sbin/"

- name: Install write_statsd plugin
  become: yes
  copy:
    src: write_statsd.py
    dest: "{{ item }}"
    mode: "0755"
  with_items:
    - "/usr/share/{{ mcac_version }}/lib/collectd/"
    - "/usr/share/{{ mcac_version_beta1 }}/lib/collectd/"

- name: Install statsd
  become: yes
  pip:
    name: statsd
    extra_args: -t /opt/collectd
    umask: "0022"
    version: "{{ statsd_version }}"

- name: Install fluent-logger
  become: yes
  pip:
    name: fluent-logger
    extra_args: -t /opt/collectd
    umask: "0022"
    version: "{{ fluent_logger_version }}"

- name: Install psutil
  become: yes
  pip:
    name: psutil

- name: Install datetime
  become: yes
  pip:
    name: datetime

- name: Install Fluent Bit # TODO: Remove this block when cassandra image is also on az linux 3
  when: '"cassandra_image" in group_names or "jump_image" in group_names'
  become: yes
  dnf:
    name: fluent-bit-3.1.9-1.azl3
    state: present
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Install Fluent Bit 3.0.6-1.azl3
  when: '"garnet_jump_image" in group_names' # TODO: Remove this condition when cassandra image is also on az linux 3
  become: yes
  dnf:
    name: fluent-bit-3.1.9-1.azl3
    state: present
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Create fluent-bit directory
  become: yes
  file:
    path: /etc/fluent-bit/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy Fluentbit config files
  become: yes
  copy:
    src: "{{ item }}"
    dest: /etc/fluent-bit/
    mode: "0644"
  with_items:
    - fluent-bit.conf
    - parsers.conf
    - format_azsecpack.lua
    
- name: Fluentbit enabled
  become: yes
  systemd:
    name: fluent-bit
    enabled: yes
    state: stopped

- name: Create nova log dir
  become: yes
  when: '"cassandra_image" in group_names'
  file:
    path: "/var/log/nova"
    state: directory
    owner: cassandra
    group: cassandra
    mode: "0755"

- name: Create nova lib dir
  become: yes
  when: '"cassandra_image" in group_names'
  file:
    path: "/var/lib/nova"
    state: directory
    owner: cassandra
    group: cassandra
    mode: "0755"

- name: Get async-profiler
  become: yes
  command: >
    az storage blob download
      --account-name {{cassandraArtifactsAccountName}}
      --container-name async-profiler
      --name async-profiler-2.9-linux-x64.tar.gz
      --file /tmp/async-profiler-2.9-linux-x64.tar.gz
      --auth-mode login 
      --output none
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Unarchive async-profiler
  become: yes
  unarchive:
    src: "/tmp/async-profiler-2.9-linux-x64.tar.gz"
    dest: "/home/azureuser/"
    remote_src: yes
  register: task_register_var
  until: task_register_var is succeeded
  retries: 5

- name: Install get-cassandra-yaml
  become: yes
  copy:
    src: get-cassandra-yaml
    dest: /usr/local/bin/
    mode: "0700"
